SELECT *
FROM IP_P_LTRMNAT
WHERE (PROD_CD, CLS_CD) IN (
    SELECT DISTINCT PROD_CD, CLS_CD
    FROM II_INFRC
    WHERE INFRC_SEQ = :infrc_seq
      AND INFRC_IDNO BETWEEN :idno_start AND :idno_end
)
