SELECT *
FROM IR_RSKRT_VAL
WHERE RSK_RT_CD IN (
    SELECT RSK_RT_CD
    FROM IP_R_RSKRT_C
    WHERE (PROD_CD, CLS_CD, COV_CD) IN (
        SELECT PROD_CD, CLS_CD, COV_CD
        FROM II_INFRC
        WHERE INFRC_SEQ = :infrc_seq
          AND INFRC_IDNO BETWEEN :idno_start AND :idno_end
    )
)
